services:
  api:
    volumes:
      - ./app:/app
    build:
      context: .
      dockerfile: api.dev.Dockerfile
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_NAME=flehmen
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306
    env_file:
      - ./app/.env
    networks:
      - flehmen
  batch:
    volumes:
      - ./batch:/app
    build:
      context: .
      dockerfile: batch.Dockerfile
    tty: true
    ports:
      - "8081:8080"
    command: ["functions-framework-python", "--target", "flehmen_batch"]
    depends_on:
      - db
    networks:
      - flehmen
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flehmen
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    tty: true
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:cached
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:cached
    networks:
      - flehmen

networks:
  flehmen:
    driver: bridge
