services:
  api:
    volumes:
      - ./app:/app
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    tty: true
    ports:
      - "8080:8080"
  batch:
    volumes:
      - ./batch:/app
    build:
      context: .
      dockerfile: Dockerfile.batch.dev
    tty: true
    ports:
      - "8081:8080"
    command: ["functions-framework-python", "--target", "flehmen_batch"]