// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"flehmen-api/ent/nextaction"
	"flehmen-api/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NextActionQuery is the builder for querying NextAction entities.
type NextActionQuery struct {
	config
	ctx        *QueryContext
	order      []nextaction.OrderOption
	inters     []Interceptor
	predicates []predicate.NextAction
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NextActionQuery builder.
func (naq *NextActionQuery) Where(ps ...predicate.NextAction) *NextActionQuery {
	naq.predicates = append(naq.predicates, ps...)
	return naq
}

// Limit the number of records to be returned by this query.
func (naq *NextActionQuery) Limit(limit int) *NextActionQuery {
	naq.ctx.Limit = &limit
	return naq
}

// Offset to start from.
func (naq *NextActionQuery) Offset(offset int) *NextActionQuery {
	naq.ctx.Offset = &offset
	return naq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (naq *NextActionQuery) Unique(unique bool) *NextActionQuery {
	naq.ctx.Unique = &unique
	return naq
}

// Order specifies how the records should be ordered.
func (naq *NextActionQuery) Order(o ...nextaction.OrderOption) *NextActionQuery {
	naq.order = append(naq.order, o...)
	return naq
}

// First returns the first NextAction entity from the query.
// Returns a *NotFoundError when no NextAction was found.
func (naq *NextActionQuery) First(ctx context.Context) (*NextAction, error) {
	nodes, err := naq.Limit(1).All(setContextOp(ctx, naq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nextaction.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (naq *NextActionQuery) FirstX(ctx context.Context) *NextAction {
	node, err := naq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NextAction ID from the query.
// Returns a *NotFoundError when no NextAction ID was found.
func (naq *NextActionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = naq.Limit(1).IDs(setContextOp(ctx, naq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nextaction.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (naq *NextActionQuery) FirstIDX(ctx context.Context) int {
	id, err := naq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NextAction entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NextAction entity is found.
// Returns a *NotFoundError when no NextAction entities are found.
func (naq *NextActionQuery) Only(ctx context.Context) (*NextAction, error) {
	nodes, err := naq.Limit(2).All(setContextOp(ctx, naq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nextaction.Label}
	default:
		return nil, &NotSingularError{nextaction.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (naq *NextActionQuery) OnlyX(ctx context.Context) *NextAction {
	node, err := naq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NextAction ID in the query.
// Returns a *NotSingularError when more than one NextAction ID is found.
// Returns a *NotFoundError when no entities are found.
func (naq *NextActionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = naq.Limit(2).IDs(setContextOp(ctx, naq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nextaction.Label}
	default:
		err = &NotSingularError{nextaction.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (naq *NextActionQuery) OnlyIDX(ctx context.Context) int {
	id, err := naq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NextActions.
func (naq *NextActionQuery) All(ctx context.Context) ([]*NextAction, error) {
	ctx = setContextOp(ctx, naq.ctx, ent.OpQueryAll)
	if err := naq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NextAction, *NextActionQuery]()
	return withInterceptors[[]*NextAction](ctx, naq, qr, naq.inters)
}

// AllX is like All, but panics if an error occurs.
func (naq *NextActionQuery) AllX(ctx context.Context) []*NextAction {
	nodes, err := naq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NextAction IDs.
func (naq *NextActionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if naq.ctx.Unique == nil && naq.path != nil {
		naq.Unique(true)
	}
	ctx = setContextOp(ctx, naq.ctx, ent.OpQueryIDs)
	if err = naq.Select(nextaction.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (naq *NextActionQuery) IDsX(ctx context.Context) []int {
	ids, err := naq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (naq *NextActionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, naq.ctx, ent.OpQueryCount)
	if err := naq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, naq, querierCount[*NextActionQuery](), naq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (naq *NextActionQuery) CountX(ctx context.Context) int {
	count, err := naq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (naq *NextActionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, naq.ctx, ent.OpQueryExist)
	switch _, err := naq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (naq *NextActionQuery) ExistX(ctx context.Context) bool {
	exist, err := naq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NextActionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (naq *NextActionQuery) Clone() *NextActionQuery {
	if naq == nil {
		return nil
	}
	return &NextActionQuery{
		config:     naq.config,
		ctx:        naq.ctx.Clone(),
		order:      append([]nextaction.OrderOption{}, naq.order...),
		inters:     append([]Interceptor{}, naq.inters...),
		predicates: append([]predicate.NextAction{}, naq.predicates...),
		// clone intermediate query.
		sql:  naq.sql.Clone(),
		path: naq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ScoreMin int `json:"score_min,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NextAction.Query().
//		GroupBy(nextaction.FieldScoreMin).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (naq *NextActionQuery) GroupBy(field string, fields ...string) *NextActionGroupBy {
	naq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NextActionGroupBy{build: naq}
	grbuild.flds = &naq.ctx.Fields
	grbuild.label = nextaction.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ScoreMin int `json:"score_min,omitempty"`
//	}
//
//	client.NextAction.Query().
//		Select(nextaction.FieldScoreMin).
//		Scan(ctx, &v)
func (naq *NextActionQuery) Select(fields ...string) *NextActionSelect {
	naq.ctx.Fields = append(naq.ctx.Fields, fields...)
	sbuild := &NextActionSelect{NextActionQuery: naq}
	sbuild.label = nextaction.Label
	sbuild.flds, sbuild.scan = &naq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NextActionSelect configured with the given aggregations.
func (naq *NextActionQuery) Aggregate(fns ...AggregateFunc) *NextActionSelect {
	return naq.Select().Aggregate(fns...)
}

func (naq *NextActionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range naq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, naq); err != nil {
				return err
			}
		}
	}
	for _, f := range naq.ctx.Fields {
		if !nextaction.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if naq.path != nil {
		prev, err := naq.path(ctx)
		if err != nil {
			return err
		}
		naq.sql = prev
	}
	return nil
}

func (naq *NextActionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NextAction, error) {
	var (
		nodes = []*NextAction{}
		_spec = naq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NextAction).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NextAction{config: naq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, naq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (naq *NextActionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := naq.querySpec()
	_spec.Node.Columns = naq.ctx.Fields
	if len(naq.ctx.Fields) > 0 {
		_spec.Unique = naq.ctx.Unique != nil && *naq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, naq.driver, _spec)
}

func (naq *NextActionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(nextaction.Table, nextaction.Columns, sqlgraph.NewFieldSpec(nextaction.FieldID, field.TypeInt))
	_spec.From = naq.sql
	if unique := naq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if naq.path != nil {
		_spec.Unique = true
	}
	if fields := naq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nextaction.FieldID)
		for i := range fields {
			if fields[i] != nextaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := naq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := naq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := naq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := naq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (naq *NextActionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(naq.driver.Dialect())
	t1 := builder.Table(nextaction.Table)
	columns := naq.ctx.Fields
	if len(columns) == 0 {
		columns = nextaction.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if naq.sql != nil {
		selector = naq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if naq.ctx.Unique != nil && *naq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range naq.predicates {
		p(selector)
	}
	for _, p := range naq.order {
		p(selector)
	}
	if offset := naq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := naq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NextActionGroupBy is the group-by builder for NextAction entities.
type NextActionGroupBy struct {
	selector
	build *NextActionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nagb *NextActionGroupBy) Aggregate(fns ...AggregateFunc) *NextActionGroupBy {
	nagb.fns = append(nagb.fns, fns...)
	return nagb
}

// Scan applies the selector query and scans the result into the given value.
func (nagb *NextActionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nagb.build.ctx, ent.OpQueryGroupBy)
	if err := nagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NextActionQuery, *NextActionGroupBy](ctx, nagb.build, nagb, nagb.build.inters, v)
}

func (nagb *NextActionGroupBy) sqlScan(ctx context.Context, root *NextActionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(nagb.fns))
	for _, fn := range nagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*nagb.flds)+len(nagb.fns))
		for _, f := range *nagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*nagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NextActionSelect is the builder for selecting fields of NextAction entities.
type NextActionSelect struct {
	*NextActionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (nas *NextActionSelect) Aggregate(fns ...AggregateFunc) *NextActionSelect {
	nas.fns = append(nas.fns, fns...)
	return nas
}

// Scan applies the selector query and scans the result into the given value.
func (nas *NextActionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nas.ctx, ent.OpQuerySelect)
	if err := nas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NextActionQuery, *NextActionSelect](ctx, nas.NextActionQuery, nas, nas.inters, v)
}

func (nas *NextActionSelect) sqlScan(ctx context.Context, root *NextActionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(nas.fns))
	for _, fn := range nas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*nas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
