// Code generated by ent, DO NOT EDIT.

package ent

import (
	"flehmen-api/ent/schema"
	"flehmen-api/ent/sukipi"
	"flehmen-api/ent/university"
	"flehmen-api/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sukipiFields := schema.Sukipi{}.Fields()
	_ = sukipiFields
	// sukipiDescCreatedAt is the schema descriptor for created_at field.
	sukipiDescCreatedAt := sukipiFields[11].Descriptor()
	// sukipi.DefaultCreatedAt holds the default value on creation for the created_at field.
	sukipi.DefaultCreatedAt = sukipiDescCreatedAt.Default.(func() time.Time)
	universityFields := schema.University{}.Fields()
	_ = universityFields
	// universityDescCreatedAt is the schema descriptor for created_at field.
	universityDescCreatedAt := universityFields[5].Descriptor()
	// university.DefaultCreatedAt holds the default value on creation for the created_at field.
	university.DefaultCreatedAt = universityDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
