// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"flehmen-api/ent/predicate"
	"flehmen-api/ent/specialevent"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpecialEventDelete is the builder for deleting a SpecialEvent entity.
type SpecialEventDelete struct {
	config
	hooks    []Hook
	mutation *SpecialEventMutation
}

// Where appends a list predicates to the SpecialEventDelete builder.
func (sed *SpecialEventDelete) Where(ps ...predicate.SpecialEvent) *SpecialEventDelete {
	sed.mutation.Where(ps...)
	return sed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sed *SpecialEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sed.sqlExec, sed.mutation, sed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sed *SpecialEventDelete) ExecX(ctx context.Context) int {
	n, err := sed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sed *SpecialEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(specialevent.Table, sqlgraph.NewFieldSpec(specialevent.FieldID, field.TypeInt))
	if ps := sed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sed.mutation.done = true
	return affected, err
}

// SpecialEventDeleteOne is the builder for deleting a single SpecialEvent entity.
type SpecialEventDeleteOne struct {
	sed *SpecialEventDelete
}

// Where appends a list predicates to the SpecialEventDelete builder.
func (sedo *SpecialEventDeleteOne) Where(ps ...predicate.SpecialEvent) *SpecialEventDeleteOne {
	sedo.sed.mutation.Where(ps...)
	return sedo
}

// Exec executes the deletion query.
func (sedo *SpecialEventDeleteOne) Exec(ctx context.Context) error {
	n, err := sedo.sed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{specialevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sedo *SpecialEventDeleteOne) ExecX(ctx context.Context) {
	if err := sedo.Exec(ctx); err != nil {
		panic(err)
	}
}
