// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"flehmen-api/ent/mbti"
	"flehmen-api/ent/predicate"
	"flehmen-api/ent/sukipi"
	"flehmen-api/ent/tweet"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SukipiUpdate is the builder for updating Sukipi entities.
type SukipiUpdate struct {
	config
	hooks    []Hook
	mutation *SukipiMutation
}

// Where appends a list predicates to the SukipiUpdate builder.
func (su *SukipiUpdate) Where(ps ...predicate.Sukipi) *SukipiUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *SukipiUpdate) SetName(s string) *SukipiUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SukipiUpdate) SetNillableName(s *string) *SukipiUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetWeight sets the "weight" field.
func (su *SukipiUpdate) SetWeight(f float64) *SukipiUpdate {
	su.mutation.ResetWeight()
	su.mutation.SetWeight(f)
	return su
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (su *SukipiUpdate) SetNillableWeight(f *float64) *SukipiUpdate {
	if f != nil {
		su.SetWeight(*f)
	}
	return su
}

// AddWeight adds f to the "weight" field.
func (su *SukipiUpdate) AddWeight(f float64) *SukipiUpdate {
	su.mutation.AddWeight(f)
	return su
}

// SetHeight sets the "height" field.
func (su *SukipiUpdate) SetHeight(f float64) *SukipiUpdate {
	su.mutation.ResetHeight()
	su.mutation.SetHeight(f)
	return su
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (su *SukipiUpdate) SetNillableHeight(f *float64) *SukipiUpdate {
	if f != nil {
		su.SetHeight(*f)
	}
	return su
}

// AddHeight adds f to the "height" field.
func (su *SukipiUpdate) AddHeight(f float64) *SukipiUpdate {
	su.mutation.AddHeight(f)
	return su
}

// SetXID sets the "x_id" field.
func (su *SukipiUpdate) SetXID(s string) *SukipiUpdate {
	su.mutation.SetXID(s)
	return su
}

// SetNillableXID sets the "x_id" field if the given value is not nil.
func (su *SukipiUpdate) SetNillableXID(s *string) *SukipiUpdate {
	if s != nil {
		su.SetXID(*s)
	}
	return su
}

// ClearXID clears the value of the "x_id" field.
func (su *SukipiUpdate) ClearXID() *SukipiUpdate {
	su.mutation.ClearXID()
	return su
}

// SetInstagramID sets the "instagram_id" field.
func (su *SukipiUpdate) SetInstagramID(s string) *SukipiUpdate {
	su.mutation.SetInstagramID(s)
	return su
}

// SetNillableInstagramID sets the "instagram_id" field if the given value is not nil.
func (su *SukipiUpdate) SetNillableInstagramID(s *string) *SukipiUpdate {
	if s != nil {
		su.SetInstagramID(*s)
	}
	return su
}

// ClearInstagramID clears the value of the "instagram_id" field.
func (su *SukipiUpdate) ClearInstagramID() *SukipiUpdate {
	su.mutation.ClearInstagramID()
	return su
}

// SetCreatedAt sets the "created_at" field.
func (su *SukipiUpdate) SetCreatedAt(t time.Time) *SukipiUpdate {
	su.mutation.SetCreatedAt(t)
	return su
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (su *SukipiUpdate) SetNillableCreatedAt(t *time.Time) *SukipiUpdate {
	if t != nil {
		su.SetCreatedAt(*t)
	}
	return su
}

// SetIsMale sets the "is_male" field.
func (su *SukipiUpdate) SetIsMale(b bool) *SukipiUpdate {
	su.mutation.SetIsMale(b)
	return su
}

// SetNillableIsMale sets the "is_male" field if the given value is not nil.
func (su *SukipiUpdate) SetNillableIsMale(b *bool) *SukipiUpdate {
	if b != nil {
		su.SetIsMale(*b)
	}
	return su
}

// SetStartAt sets the "start_at" field.
func (su *SukipiUpdate) SetStartAt(t time.Time) *SukipiUpdate {
	su.mutation.SetStartAt(t)
	return su
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (su *SukipiUpdate) SetNillableStartAt(t *time.Time) *SukipiUpdate {
	if t != nil {
		su.SetStartAt(*t)
	}
	return su
}

// ClearStartAt clears the value of the "start_at" field.
func (su *SukipiUpdate) ClearStartAt() *SukipiUpdate {
	su.mutation.ClearStartAt()
	return su
}

// SetMbtiID sets the "mbti" edge to the Mbti entity by ID.
func (su *SukipiUpdate) SetMbtiID(id int) *SukipiUpdate {
	su.mutation.SetMbtiID(id)
	return su
}

// SetNillableMbtiID sets the "mbti" edge to the Mbti entity by ID if the given value is not nil.
func (su *SukipiUpdate) SetNillableMbtiID(id *int) *SukipiUpdate {
	if id != nil {
		su = su.SetMbtiID(*id)
	}
	return su
}

// SetMbti sets the "mbti" edge to the Mbti entity.
func (su *SukipiUpdate) SetMbti(m *Mbti) *SukipiUpdate {
	return su.SetMbtiID(m.ID)
}

// AddTweetIDs adds the "tweets" edge to the Tweet entity by IDs.
func (su *SukipiUpdate) AddTweetIDs(ids ...int) *SukipiUpdate {
	su.mutation.AddTweetIDs(ids...)
	return su
}

// AddTweets adds the "tweets" edges to the Tweet entity.
func (su *SukipiUpdate) AddTweets(t ...*Tweet) *SukipiUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return su.AddTweetIDs(ids...)
}

// Mutation returns the SukipiMutation object of the builder.
func (su *SukipiUpdate) Mutation() *SukipiMutation {
	return su.mutation
}

// ClearMbti clears the "mbti" edge to the Mbti entity.
func (su *SukipiUpdate) ClearMbti() *SukipiUpdate {
	su.mutation.ClearMbti()
	return su
}

// ClearTweets clears all "tweets" edges to the Tweet entity.
func (su *SukipiUpdate) ClearTweets() *SukipiUpdate {
	su.mutation.ClearTweets()
	return su
}

// RemoveTweetIDs removes the "tweets" edge to Tweet entities by IDs.
func (su *SukipiUpdate) RemoveTweetIDs(ids ...int) *SukipiUpdate {
	su.mutation.RemoveTweetIDs(ids...)
	return su
}

// RemoveTweets removes "tweets" edges to Tweet entities.
func (su *SukipiUpdate) RemoveTweets(t ...*Tweet) *SukipiUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return su.RemoveTweetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SukipiUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SukipiUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SukipiUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SukipiUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SukipiUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sukipi.Table, sukipi.Columns, sqlgraph.NewFieldSpec(sukipi.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(sukipi.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.Weight(); ok {
		_spec.SetField(sukipi.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedWeight(); ok {
		_spec.AddField(sukipi.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.Height(); ok {
		_spec.SetField(sukipi.FieldHeight, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedHeight(); ok {
		_spec.AddField(sukipi.FieldHeight, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.XID(); ok {
		_spec.SetField(sukipi.FieldXID, field.TypeString, value)
	}
	if su.mutation.XIDCleared() {
		_spec.ClearField(sukipi.FieldXID, field.TypeString)
	}
	if value, ok := su.mutation.InstagramID(); ok {
		_spec.SetField(sukipi.FieldInstagramID, field.TypeString, value)
	}
	if su.mutation.InstagramIDCleared() {
		_spec.ClearField(sukipi.FieldInstagramID, field.TypeString)
	}
	if value, ok := su.mutation.CreatedAt(); ok {
		_spec.SetField(sukipi.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.IsMale(); ok {
		_spec.SetField(sukipi.FieldIsMale, field.TypeBool, value)
	}
	if value, ok := su.mutation.StartAt(); ok {
		_spec.SetField(sukipi.FieldStartAt, field.TypeTime, value)
	}
	if su.mutation.StartAtCleared() {
		_spec.ClearField(sukipi.FieldStartAt, field.TypeTime)
	}
	if su.mutation.MbtiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sukipi.MbtiTable,
			Columns: []string{sukipi.MbtiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mbti.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.MbtiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sukipi.MbtiTable,
			Columns: []string{sukipi.MbtiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mbti.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.TweetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sukipi.TweetsTable,
			Columns: []string{sukipi.TweetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedTweetsIDs(); len(nodes) > 0 && !su.mutation.TweetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sukipi.TweetsTable,
			Columns: []string{sukipi.TweetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.TweetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sukipi.TweetsTable,
			Columns: []string{sukipi.TweetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sukipi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SukipiUpdateOne is the builder for updating a single Sukipi entity.
type SukipiUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SukipiMutation
}

// SetName sets the "name" field.
func (suo *SukipiUpdateOne) SetName(s string) *SukipiUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SukipiUpdateOne) SetNillableName(s *string) *SukipiUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetWeight sets the "weight" field.
func (suo *SukipiUpdateOne) SetWeight(f float64) *SukipiUpdateOne {
	suo.mutation.ResetWeight()
	suo.mutation.SetWeight(f)
	return suo
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (suo *SukipiUpdateOne) SetNillableWeight(f *float64) *SukipiUpdateOne {
	if f != nil {
		suo.SetWeight(*f)
	}
	return suo
}

// AddWeight adds f to the "weight" field.
func (suo *SukipiUpdateOne) AddWeight(f float64) *SukipiUpdateOne {
	suo.mutation.AddWeight(f)
	return suo
}

// SetHeight sets the "height" field.
func (suo *SukipiUpdateOne) SetHeight(f float64) *SukipiUpdateOne {
	suo.mutation.ResetHeight()
	suo.mutation.SetHeight(f)
	return suo
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (suo *SukipiUpdateOne) SetNillableHeight(f *float64) *SukipiUpdateOne {
	if f != nil {
		suo.SetHeight(*f)
	}
	return suo
}

// AddHeight adds f to the "height" field.
func (suo *SukipiUpdateOne) AddHeight(f float64) *SukipiUpdateOne {
	suo.mutation.AddHeight(f)
	return suo
}

// SetXID sets the "x_id" field.
func (suo *SukipiUpdateOne) SetXID(s string) *SukipiUpdateOne {
	suo.mutation.SetXID(s)
	return suo
}

// SetNillableXID sets the "x_id" field if the given value is not nil.
func (suo *SukipiUpdateOne) SetNillableXID(s *string) *SukipiUpdateOne {
	if s != nil {
		suo.SetXID(*s)
	}
	return suo
}

// ClearXID clears the value of the "x_id" field.
func (suo *SukipiUpdateOne) ClearXID() *SukipiUpdateOne {
	suo.mutation.ClearXID()
	return suo
}

// SetInstagramID sets the "instagram_id" field.
func (suo *SukipiUpdateOne) SetInstagramID(s string) *SukipiUpdateOne {
	suo.mutation.SetInstagramID(s)
	return suo
}

// SetNillableInstagramID sets the "instagram_id" field if the given value is not nil.
func (suo *SukipiUpdateOne) SetNillableInstagramID(s *string) *SukipiUpdateOne {
	if s != nil {
		suo.SetInstagramID(*s)
	}
	return suo
}

// ClearInstagramID clears the value of the "instagram_id" field.
func (suo *SukipiUpdateOne) ClearInstagramID() *SukipiUpdateOne {
	suo.mutation.ClearInstagramID()
	return suo
}

// SetCreatedAt sets the "created_at" field.
func (suo *SukipiUpdateOne) SetCreatedAt(t time.Time) *SukipiUpdateOne {
	suo.mutation.SetCreatedAt(t)
	return suo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (suo *SukipiUpdateOne) SetNillableCreatedAt(t *time.Time) *SukipiUpdateOne {
	if t != nil {
		suo.SetCreatedAt(*t)
	}
	return suo
}

// SetIsMale sets the "is_male" field.
func (suo *SukipiUpdateOne) SetIsMale(b bool) *SukipiUpdateOne {
	suo.mutation.SetIsMale(b)
	return suo
}

// SetNillableIsMale sets the "is_male" field if the given value is not nil.
func (suo *SukipiUpdateOne) SetNillableIsMale(b *bool) *SukipiUpdateOne {
	if b != nil {
		suo.SetIsMale(*b)
	}
	return suo
}

// SetStartAt sets the "start_at" field.
func (suo *SukipiUpdateOne) SetStartAt(t time.Time) *SukipiUpdateOne {
	suo.mutation.SetStartAt(t)
	return suo
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (suo *SukipiUpdateOne) SetNillableStartAt(t *time.Time) *SukipiUpdateOne {
	if t != nil {
		suo.SetStartAt(*t)
	}
	return suo
}

// ClearStartAt clears the value of the "start_at" field.
func (suo *SukipiUpdateOne) ClearStartAt() *SukipiUpdateOne {
	suo.mutation.ClearStartAt()
	return suo
}

// SetMbtiID sets the "mbti" edge to the Mbti entity by ID.
func (suo *SukipiUpdateOne) SetMbtiID(id int) *SukipiUpdateOne {
	suo.mutation.SetMbtiID(id)
	return suo
}

// SetNillableMbtiID sets the "mbti" edge to the Mbti entity by ID if the given value is not nil.
func (suo *SukipiUpdateOne) SetNillableMbtiID(id *int) *SukipiUpdateOne {
	if id != nil {
		suo = suo.SetMbtiID(*id)
	}
	return suo
}

// SetMbti sets the "mbti" edge to the Mbti entity.
func (suo *SukipiUpdateOne) SetMbti(m *Mbti) *SukipiUpdateOne {
	return suo.SetMbtiID(m.ID)
}

// AddTweetIDs adds the "tweets" edge to the Tweet entity by IDs.
func (suo *SukipiUpdateOne) AddTweetIDs(ids ...int) *SukipiUpdateOne {
	suo.mutation.AddTweetIDs(ids...)
	return suo
}

// AddTweets adds the "tweets" edges to the Tweet entity.
func (suo *SukipiUpdateOne) AddTweets(t ...*Tweet) *SukipiUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return suo.AddTweetIDs(ids...)
}

// Mutation returns the SukipiMutation object of the builder.
func (suo *SukipiUpdateOne) Mutation() *SukipiMutation {
	return suo.mutation
}

// ClearMbti clears the "mbti" edge to the Mbti entity.
func (suo *SukipiUpdateOne) ClearMbti() *SukipiUpdateOne {
	suo.mutation.ClearMbti()
	return suo
}

// ClearTweets clears all "tweets" edges to the Tweet entity.
func (suo *SukipiUpdateOne) ClearTweets() *SukipiUpdateOne {
	suo.mutation.ClearTweets()
	return suo
}

// RemoveTweetIDs removes the "tweets" edge to Tweet entities by IDs.
func (suo *SukipiUpdateOne) RemoveTweetIDs(ids ...int) *SukipiUpdateOne {
	suo.mutation.RemoveTweetIDs(ids...)
	return suo
}

// RemoveTweets removes "tweets" edges to Tweet entities.
func (suo *SukipiUpdateOne) RemoveTweets(t ...*Tweet) *SukipiUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return suo.RemoveTweetIDs(ids...)
}

// Where appends a list predicates to the SukipiUpdate builder.
func (suo *SukipiUpdateOne) Where(ps ...predicate.Sukipi) *SukipiUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SukipiUpdateOne) Select(field string, fields ...string) *SukipiUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Sukipi entity.
func (suo *SukipiUpdateOne) Save(ctx context.Context) (*Sukipi, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SukipiUpdateOne) SaveX(ctx context.Context) *Sukipi {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SukipiUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SukipiUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SukipiUpdateOne) sqlSave(ctx context.Context) (_node *Sukipi, err error) {
	_spec := sqlgraph.NewUpdateSpec(sukipi.Table, sukipi.Columns, sqlgraph.NewFieldSpec(sukipi.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sukipi.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sukipi.FieldID)
		for _, f := range fields {
			if !sukipi.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sukipi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(sukipi.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Weight(); ok {
		_spec.SetField(sukipi.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedWeight(); ok {
		_spec.AddField(sukipi.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.Height(); ok {
		_spec.SetField(sukipi.FieldHeight, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedHeight(); ok {
		_spec.AddField(sukipi.FieldHeight, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.XID(); ok {
		_spec.SetField(sukipi.FieldXID, field.TypeString, value)
	}
	if suo.mutation.XIDCleared() {
		_spec.ClearField(sukipi.FieldXID, field.TypeString)
	}
	if value, ok := suo.mutation.InstagramID(); ok {
		_spec.SetField(sukipi.FieldInstagramID, field.TypeString, value)
	}
	if suo.mutation.InstagramIDCleared() {
		_spec.ClearField(sukipi.FieldInstagramID, field.TypeString)
	}
	if value, ok := suo.mutation.CreatedAt(); ok {
		_spec.SetField(sukipi.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.IsMale(); ok {
		_spec.SetField(sukipi.FieldIsMale, field.TypeBool, value)
	}
	if value, ok := suo.mutation.StartAt(); ok {
		_spec.SetField(sukipi.FieldStartAt, field.TypeTime, value)
	}
	if suo.mutation.StartAtCleared() {
		_spec.ClearField(sukipi.FieldStartAt, field.TypeTime)
	}
	if suo.mutation.MbtiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sukipi.MbtiTable,
			Columns: []string{sukipi.MbtiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mbti.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.MbtiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sukipi.MbtiTable,
			Columns: []string{sukipi.MbtiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mbti.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.TweetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sukipi.TweetsTable,
			Columns: []string{sukipi.TweetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedTweetsIDs(); len(nodes) > 0 && !suo.mutation.TweetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sukipi.TweetsTable,
			Columns: []string{sukipi.TweetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.TweetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sukipi.TweetsTable,
			Columns: []string{sukipi.TweetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Sukipi{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sukipi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
