// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"flehmen-api/ent/mbti"
	"flehmen-api/ent/sukipi"
	"flehmen-api/ent/tweet"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SukipiCreate is the builder for creating a Sukipi entity.
type SukipiCreate struct {
	config
	mutation *SukipiMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sc *SukipiCreate) SetName(s string) *SukipiCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetWeight sets the "weight" field.
func (sc *SukipiCreate) SetWeight(f float64) *SukipiCreate {
	sc.mutation.SetWeight(f)
	return sc
}

// SetHeight sets the "height" field.
func (sc *SukipiCreate) SetHeight(f float64) *SukipiCreate {
	sc.mutation.SetHeight(f)
	return sc
}

// SetXID sets the "x_id" field.
func (sc *SukipiCreate) SetXID(s string) *SukipiCreate {
	sc.mutation.SetXID(s)
	return sc
}

// SetNillableXID sets the "x_id" field if the given value is not nil.
func (sc *SukipiCreate) SetNillableXID(s *string) *SukipiCreate {
	if s != nil {
		sc.SetXID(*s)
	}
	return sc
}

// SetInstagramID sets the "instagram_id" field.
func (sc *SukipiCreate) SetInstagramID(s string) *SukipiCreate {
	sc.mutation.SetInstagramID(s)
	return sc
}

// SetNillableInstagramID sets the "instagram_id" field if the given value is not nil.
func (sc *SukipiCreate) SetNillableInstagramID(s *string) *SukipiCreate {
	if s != nil {
		sc.SetInstagramID(*s)
	}
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *SukipiCreate) SetCreatedAt(t time.Time) *SukipiCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SukipiCreate) SetNillableCreatedAt(t *time.Time) *SukipiCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetIsMale sets the "is_male" field.
func (sc *SukipiCreate) SetIsMale(b bool) *SukipiCreate {
	sc.mutation.SetIsMale(b)
	return sc
}

// SetStartAt sets the "start_at" field.
func (sc *SukipiCreate) SetStartAt(t time.Time) *SukipiCreate {
	sc.mutation.SetStartAt(t)
	return sc
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (sc *SukipiCreate) SetNillableStartAt(t *time.Time) *SukipiCreate {
	if t != nil {
		sc.SetStartAt(*t)
	}
	return sc
}

// SetMbtiID sets the "mbti" edge to the Mbti entity by ID.
func (sc *SukipiCreate) SetMbtiID(id int) *SukipiCreate {
	sc.mutation.SetMbtiID(id)
	return sc
}

// SetNillableMbtiID sets the "mbti" edge to the Mbti entity by ID if the given value is not nil.
func (sc *SukipiCreate) SetNillableMbtiID(id *int) *SukipiCreate {
	if id != nil {
		sc = sc.SetMbtiID(*id)
	}
	return sc
}

// SetMbti sets the "mbti" edge to the Mbti entity.
func (sc *SukipiCreate) SetMbti(m *Mbti) *SukipiCreate {
	return sc.SetMbtiID(m.ID)
}

// AddTweetIDs adds the "tweets" edge to the Tweet entity by IDs.
func (sc *SukipiCreate) AddTweetIDs(ids ...int) *SukipiCreate {
	sc.mutation.AddTweetIDs(ids...)
	return sc
}

// AddTweets adds the "tweets" edges to the Tweet entity.
func (sc *SukipiCreate) AddTweets(t ...*Tweet) *SukipiCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return sc.AddTweetIDs(ids...)
}

// Mutation returns the SukipiMutation object of the builder.
func (sc *SukipiCreate) Mutation() *SukipiMutation {
	return sc.mutation
}

// Save creates the Sukipi in the database.
func (sc *SukipiCreate) Save(ctx context.Context) (*Sukipi, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SukipiCreate) SaveX(ctx context.Context) *Sukipi {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SukipiCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SukipiCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SukipiCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := sukipi.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SukipiCreate) check() error {
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Sukipi.name"`)}
	}
	if _, ok := sc.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "Sukipi.weight"`)}
	}
	if _, ok := sc.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "Sukipi.height"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Sukipi.created_at"`)}
	}
	if _, ok := sc.mutation.IsMale(); !ok {
		return &ValidationError{Name: "is_male", err: errors.New(`ent: missing required field "Sukipi.is_male"`)}
	}
	return nil
}

func (sc *SukipiCreate) sqlSave(ctx context.Context) (*Sukipi, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SukipiCreate) createSpec() (*Sukipi, *sqlgraph.CreateSpec) {
	var (
		_node = &Sukipi{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(sukipi.Table, sqlgraph.NewFieldSpec(sukipi.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(sukipi.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.Weight(); ok {
		_spec.SetField(sukipi.FieldWeight, field.TypeFloat64, value)
		_node.Weight = value
	}
	if value, ok := sc.mutation.Height(); ok {
		_spec.SetField(sukipi.FieldHeight, field.TypeFloat64, value)
		_node.Height = value
	}
	if value, ok := sc.mutation.XID(); ok {
		_spec.SetField(sukipi.FieldXID, field.TypeString, value)
		_node.XID = value
	}
	if value, ok := sc.mutation.InstagramID(); ok {
		_spec.SetField(sukipi.FieldInstagramID, field.TypeString, value)
		_node.InstagramID = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(sukipi.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.IsMale(); ok {
		_spec.SetField(sukipi.FieldIsMale, field.TypeBool, value)
		_node.IsMale = value
	}
	if value, ok := sc.mutation.StartAt(); ok {
		_spec.SetField(sukipi.FieldStartAt, field.TypeTime, value)
		_node.StartAt = value
	}
	if nodes := sc.mutation.MbtiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sukipi.MbtiTable,
			Columns: []string{sukipi.MbtiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mbti.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.sukipi_mbti = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.TweetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sukipi.TweetsTable,
			Columns: []string{sukipi.TweetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SukipiCreateBulk is the builder for creating many Sukipi entities in bulk.
type SukipiCreateBulk struct {
	config
	err      error
	builders []*SukipiCreate
}

// Save creates the Sukipi entities in the database.
func (scb *SukipiCreateBulk) Save(ctx context.Context) ([]*Sukipi, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Sukipi, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SukipiMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SukipiCreateBulk) SaveX(ctx context.Context) []*Sukipi {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SukipiCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SukipiCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
