// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"flehmen-api/ent/predicate"
	"flehmen-api/ent/twitteruser"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TwitterUserDelete is the builder for deleting a TwitterUser entity.
type TwitterUserDelete struct {
	config
	hooks    []Hook
	mutation *TwitterUserMutation
}

// Where appends a list predicates to the TwitterUserDelete builder.
func (tud *TwitterUserDelete) Where(ps ...predicate.TwitterUser) *TwitterUserDelete {
	tud.mutation.Where(ps...)
	return tud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tud *TwitterUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tud.sqlExec, tud.mutation, tud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tud *TwitterUserDelete) ExecX(ctx context.Context) int {
	n, err := tud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tud *TwitterUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(twitteruser.Table, sqlgraph.NewFieldSpec(twitteruser.FieldID, field.TypeInt))
	if ps := tud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tud.mutation.done = true
	return affected, err
}

// TwitterUserDeleteOne is the builder for deleting a single TwitterUser entity.
type TwitterUserDeleteOne struct {
	tud *TwitterUserDelete
}

// Where appends a list predicates to the TwitterUserDelete builder.
func (tudo *TwitterUserDeleteOne) Where(ps ...predicate.TwitterUser) *TwitterUserDeleteOne {
	tudo.tud.mutation.Where(ps...)
	return tudo
}

// Exec executes the deletion query.
func (tudo *TwitterUserDeleteOne) Exec(ctx context.Context) error {
	n, err := tudo.tud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{twitteruser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tudo *TwitterUserDeleteOne) ExecX(ctx context.Context) {
	if err := tudo.Exec(ctx); err != nil {
		panic(err)
	}
}
