// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"flehmen-api/ent/predicate"
	"flehmen-api/ent/university"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UniversityUpdate is the builder for updating University entities.
type UniversityUpdate struct {
	config
	hooks    []Hook
	mutation *UniversityMutation
}

// Where appends a list predicates to the UniversityUpdate builder.
func (uu *UniversityUpdate) Where(ps ...predicate.University) *UniversityUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetName sets the "name" field.
func (uu *UniversityUpdate) SetName(s string) *UniversityUpdate {
	uu.mutation.SetName(s)
	return uu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uu *UniversityUpdate) SetNillableName(s *string) *UniversityUpdate {
	if s != nil {
		uu.SetName(*s)
	}
	return uu
}

// SetDeviationLowerValue sets the "deviationLowerValue" field.
func (uu *UniversityUpdate) SetDeviationLowerValue(i int) *UniversityUpdate {
	uu.mutation.ResetDeviationLowerValue()
	uu.mutation.SetDeviationLowerValue(i)
	return uu
}

// SetNillableDeviationLowerValue sets the "deviationLowerValue" field if the given value is not nil.
func (uu *UniversityUpdate) SetNillableDeviationLowerValue(i *int) *UniversityUpdate {
	if i != nil {
		uu.SetDeviationLowerValue(*i)
	}
	return uu
}

// AddDeviationLowerValue adds i to the "deviationLowerValue" field.
func (uu *UniversityUpdate) AddDeviationLowerValue(i int) *UniversityUpdate {
	uu.mutation.AddDeviationLowerValue(i)
	return uu
}

// SetDeviationUpperValue sets the "deviationUpperValue" field.
func (uu *UniversityUpdate) SetDeviationUpperValue(i int) *UniversityUpdate {
	uu.mutation.ResetDeviationUpperValue()
	uu.mutation.SetDeviationUpperValue(i)
	return uu
}

// SetNillableDeviationUpperValue sets the "deviationUpperValue" field if the given value is not nil.
func (uu *UniversityUpdate) SetNillableDeviationUpperValue(i *int) *UniversityUpdate {
	if i != nil {
		uu.SetDeviationUpperValue(*i)
	}
	return uu
}

// AddDeviationUpperValue adds i to the "deviationUpperValue" field.
func (uu *UniversityUpdate) AddDeviationUpperValue(i int) *UniversityUpdate {
	uu.mutation.AddDeviationUpperValue(i)
	return uu
}

// SetAbbreviation sets the "abbreviation" field.
func (uu *UniversityUpdate) SetAbbreviation(s string) *UniversityUpdate {
	uu.mutation.SetAbbreviation(s)
	return uu
}

// SetNillableAbbreviation sets the "abbreviation" field if the given value is not nil.
func (uu *UniversityUpdate) SetNillableAbbreviation(s *string) *UniversityUpdate {
	if s != nil {
		uu.SetAbbreviation(*s)
	}
	return uu
}

// SetPrefecture sets the "prefecture" field.
func (uu *UniversityUpdate) SetPrefecture(s string) *UniversityUpdate {
	uu.mutation.SetPrefecture(s)
	return uu
}

// SetNillablePrefecture sets the "prefecture" field if the given value is not nil.
func (uu *UniversityUpdate) SetNillablePrefecture(s *string) *UniversityUpdate {
	if s != nil {
		uu.SetPrefecture(*s)
	}
	return uu
}

// SetCreatedAt sets the "created_at" field.
func (uu *UniversityUpdate) SetCreatedAt(t time.Time) *UniversityUpdate {
	uu.mutation.SetCreatedAt(t)
	return uu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uu *UniversityUpdate) SetNillableCreatedAt(t *time.Time) *UniversityUpdate {
	if t != nil {
		uu.SetCreatedAt(*t)
	}
	return uu
}

// Mutation returns the UniversityMutation object of the builder.
func (uu *UniversityUpdate) Mutation() *UniversityMutation {
	return uu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UniversityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UniversityUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UniversityUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UniversityUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UniversityUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(university.Table, university.Columns, sqlgraph.NewFieldSpec(university.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Name(); ok {
		_spec.SetField(university.FieldName, field.TypeString, value)
	}
	if value, ok := uu.mutation.DeviationLowerValue(); ok {
		_spec.SetField(university.FieldDeviationLowerValue, field.TypeInt, value)
	}
	if value, ok := uu.mutation.AddedDeviationLowerValue(); ok {
		_spec.AddField(university.FieldDeviationLowerValue, field.TypeInt, value)
	}
	if value, ok := uu.mutation.DeviationUpperValue(); ok {
		_spec.SetField(university.FieldDeviationUpperValue, field.TypeInt, value)
	}
	if value, ok := uu.mutation.AddedDeviationUpperValue(); ok {
		_spec.AddField(university.FieldDeviationUpperValue, field.TypeInt, value)
	}
	if value, ok := uu.mutation.Abbreviation(); ok {
		_spec.SetField(university.FieldAbbreviation, field.TypeString, value)
	}
	if value, ok := uu.mutation.Prefecture(); ok {
		_spec.SetField(university.FieldPrefecture, field.TypeString, value)
	}
	if value, ok := uu.mutation.CreatedAt(); ok {
		_spec.SetField(university.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{university.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UniversityUpdateOne is the builder for updating a single University entity.
type UniversityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UniversityMutation
}

// SetName sets the "name" field.
func (uuo *UniversityUpdateOne) SetName(s string) *UniversityUpdateOne {
	uuo.mutation.SetName(s)
	return uuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uuo *UniversityUpdateOne) SetNillableName(s *string) *UniversityUpdateOne {
	if s != nil {
		uuo.SetName(*s)
	}
	return uuo
}

// SetDeviationLowerValue sets the "deviationLowerValue" field.
func (uuo *UniversityUpdateOne) SetDeviationLowerValue(i int) *UniversityUpdateOne {
	uuo.mutation.ResetDeviationLowerValue()
	uuo.mutation.SetDeviationLowerValue(i)
	return uuo
}

// SetNillableDeviationLowerValue sets the "deviationLowerValue" field if the given value is not nil.
func (uuo *UniversityUpdateOne) SetNillableDeviationLowerValue(i *int) *UniversityUpdateOne {
	if i != nil {
		uuo.SetDeviationLowerValue(*i)
	}
	return uuo
}

// AddDeviationLowerValue adds i to the "deviationLowerValue" field.
func (uuo *UniversityUpdateOne) AddDeviationLowerValue(i int) *UniversityUpdateOne {
	uuo.mutation.AddDeviationLowerValue(i)
	return uuo
}

// SetDeviationUpperValue sets the "deviationUpperValue" field.
func (uuo *UniversityUpdateOne) SetDeviationUpperValue(i int) *UniversityUpdateOne {
	uuo.mutation.ResetDeviationUpperValue()
	uuo.mutation.SetDeviationUpperValue(i)
	return uuo
}

// SetNillableDeviationUpperValue sets the "deviationUpperValue" field if the given value is not nil.
func (uuo *UniversityUpdateOne) SetNillableDeviationUpperValue(i *int) *UniversityUpdateOne {
	if i != nil {
		uuo.SetDeviationUpperValue(*i)
	}
	return uuo
}

// AddDeviationUpperValue adds i to the "deviationUpperValue" field.
func (uuo *UniversityUpdateOne) AddDeviationUpperValue(i int) *UniversityUpdateOne {
	uuo.mutation.AddDeviationUpperValue(i)
	return uuo
}

// SetAbbreviation sets the "abbreviation" field.
func (uuo *UniversityUpdateOne) SetAbbreviation(s string) *UniversityUpdateOne {
	uuo.mutation.SetAbbreviation(s)
	return uuo
}

// SetNillableAbbreviation sets the "abbreviation" field if the given value is not nil.
func (uuo *UniversityUpdateOne) SetNillableAbbreviation(s *string) *UniversityUpdateOne {
	if s != nil {
		uuo.SetAbbreviation(*s)
	}
	return uuo
}

// SetPrefecture sets the "prefecture" field.
func (uuo *UniversityUpdateOne) SetPrefecture(s string) *UniversityUpdateOne {
	uuo.mutation.SetPrefecture(s)
	return uuo
}

// SetNillablePrefecture sets the "prefecture" field if the given value is not nil.
func (uuo *UniversityUpdateOne) SetNillablePrefecture(s *string) *UniversityUpdateOne {
	if s != nil {
		uuo.SetPrefecture(*s)
	}
	return uuo
}

// SetCreatedAt sets the "created_at" field.
func (uuo *UniversityUpdateOne) SetCreatedAt(t time.Time) *UniversityUpdateOne {
	uuo.mutation.SetCreatedAt(t)
	return uuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uuo *UniversityUpdateOne) SetNillableCreatedAt(t *time.Time) *UniversityUpdateOne {
	if t != nil {
		uuo.SetCreatedAt(*t)
	}
	return uuo
}

// Mutation returns the UniversityMutation object of the builder.
func (uuo *UniversityUpdateOne) Mutation() *UniversityMutation {
	return uuo.mutation
}

// Where appends a list predicates to the UniversityUpdate builder.
func (uuo *UniversityUpdateOne) Where(ps ...predicate.University) *UniversityUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UniversityUpdateOne) Select(field string, fields ...string) *UniversityUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated University entity.
func (uuo *UniversityUpdateOne) Save(ctx context.Context) (*University, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UniversityUpdateOne) SaveX(ctx context.Context) *University {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UniversityUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UniversityUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UniversityUpdateOne) sqlSave(ctx context.Context) (_node *University, err error) {
	_spec := sqlgraph.NewUpdateSpec(university.Table, university.Columns, sqlgraph.NewFieldSpec(university.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "University.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, university.FieldID)
		for _, f := range fields {
			if !university.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != university.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Name(); ok {
		_spec.SetField(university.FieldName, field.TypeString, value)
	}
	if value, ok := uuo.mutation.DeviationLowerValue(); ok {
		_spec.SetField(university.FieldDeviationLowerValue, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.AddedDeviationLowerValue(); ok {
		_spec.AddField(university.FieldDeviationLowerValue, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.DeviationUpperValue(); ok {
		_spec.SetField(university.FieldDeviationUpperValue, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.AddedDeviationUpperValue(); ok {
		_spec.AddField(university.FieldDeviationUpperValue, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.Abbreviation(); ok {
		_spec.SetField(university.FieldAbbreviation, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Prefecture(); ok {
		_spec.SetField(university.FieldPrefecture, field.TypeString, value)
	}
	if value, ok := uuo.mutation.CreatedAt(); ok {
		_spec.SetField(university.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &University{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{university.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
