-- Create "mbtis" table
CREATE TABLE `mbtis` (`id` bigint NOT NULL AUTO_INCREMENT, `type` varchar(255) NOT NULL, `created_at` timestamp NOT NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "users" table
CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `weight` double NOT NULL, `height` double NOT NULL, `clerk_id` varchar(255) NOT NULL, `is_male` bool NOT NULL, `created_at` timestamp NOT NULL, `user_mbti` bigint NULL, PRIMARY KEY (`id`), UNIQUE INDEX `clerk_id` (`clerk_id`), INDEX `users_mbtis_mbti` (`user_mbti`), CONSTRAINT `users_mbtis_mbti` FOREIGN KEY (`user_mbti`) REFERENCES `mbtis` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "special_events" table
CREATE TABLE `special_events` (`id` bigint NOT NULL AUTO_INCREMENT, `occured_at` timestamp NOT NULL, `title` varchar(255) NOT NULL, `detail_comment` varchar(255) NOT NULL, `user_special_events` bigint NULL, PRIMARY KEY (`id`), INDEX `special_events_users_special_events` (`user_special_events`), CONSTRAINT `special_events_users_special_events` FOREIGN KEY (`user_special_events`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "sukipis" table
CREATE TABLE `sukipis` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `weight` double NOT NULL, `height` double NOT NULL, `x_id` varchar(255) NOT NULL, `instagram_id` varchar(255) NOT NULL, `created_at` timestamp NOT NULL, `is_male` bool NOT NULL, `start_at` timestamp NULL, `sukipi_mbti` bigint NULL, PRIMARY KEY (`id`), INDEX `sukipis_mbtis_mbti` (`sukipi_mbti`), CONSTRAINT `sukipis_mbtis_mbti` FOREIGN KEY (`sukipi_mbti`) REFERENCES `mbtis` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "tweets" table
CREATE TABLE `tweets` (`id` bigint NOT NULL AUTO_INCREMENT, `text` varchar(255) NOT NULL, `tweet_id` bigint NOT NULL, `tweet_created_at` timestamp NOT NULL, `created_at` timestamp NOT NULL, `sukipi_tweets` bigint NULL, PRIMARY KEY (`id`), INDEX `tweets_sukipis_tweets` (`sukipi_tweets`), CONSTRAINT `tweets_sukipis_tweets` FOREIGN KEY (`sukipi_tweets`) REFERENCES `sukipis` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
